// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  raceKey: __t.i32().name("race_key"),
  name: __t.string(),
  meetingName: __t.string().name("meeting_name"),
  location: __t.string(),
  date: __t.string(),
  circuitKey: __t.i32().name("circuit_key"),
  status: __t.string(),
  seasonYear: __t.i32().name("season_year"),
});
