// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  driverNumber: __t.i32(),
  sessionKey: __t.i32(),
  timestamp: __t.string(),
  speed: __t.i32(),
  rpm: __t.i32(),
  gear: __t.i8(),
  throttle: __t.i8(),
  brake: __t.i8(),
  drs: __t.i8(),
  x: __t.f64(),
  y: __t.f64(),
};
