// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AuthMapping = __t.object("AuthMapping", {
  clerkId: __t.string(),
  identity: __t.identity(),
});
export type AuthMapping = __Infer<typeof AuthMapping>;

export const Config = __t.object("Config", {
  key: __t.string(),
  value: __t.string(),
});
export type Config = __Infer<typeof Config>;

export const Driver = __t.object("Driver", {
  driverNumber: __t.i32(),
  name: __t.string(),
  team: __t.string(),
  teamColor: __t.string(),
});
export type Driver = __Infer<typeof Driver>;

export const Race = __t.object("Race", {
  raceKey: __t.i32(),
  name: __t.string(),
  date: __t.string(),
  circuitKey: __t.i32(),
  status: __t.string(),
  seasonYear: __t.i32(),
});
export type Race = __Infer<typeof Race>;

export const Telemetry = __t.object("Telemetry", {
  driverNumber: __t.i32(),
  sessionKey: __t.i32(),
  timestamp: __t.string(),
  speed: __t.i32(),
  rpm: __t.i32(),
  gear: __t.i8(),
  throttle: __t.i8(),
  brake: __t.i8(),
  drs: __t.i8(),
  x: __t.f64(),
  y: __t.f64(),
});
export type Telemetry = __Infer<typeof Telemetry>;

export const TrackPoint = __t.object("TrackPoint", {
  circuitKey: __t.i32(),
  order: __t.i32(),
  x: __t.f64(),
  y: __t.f64(),
});
export type TrackPoint = __Infer<typeof TrackPoint>;

